import { videos } from "./videosAnim"

const es = {
    tituloPrincipal: "Motion Graphics y Edición de Video aplicado a estrategias de marketing",
    texto1Servicio: "Hablamos el idioma del diseño, animación y video, pero lo que nos hace únicos es que sabemos conectarlo con el mundo del marketing y la publicidad.",
    texto2Servicio: "Analizamos la necesidad de cada cliente para brindar soluciones reales a objetivos concretos y alcanzar resultados exitosos.",
    tituloMotion: "¿Qué se puede hacer con Motion Graphics?",
    videosMotion: videos,
    tituloProceso: "Proceso de Producción",
    procesoSubtitulo1: "1. Primero, investigar.",
    procesoSub1Texto1: "Es fundamental investigar la personalidad de la marca, su esencia y la de sus competidores.",
    procesoSub1Texto2: "Permite ser precisos en un mar de información: porque allana el camino y ofrece un terreno sólido sobre el cual avanzar firmemente.",
    procesoSub1Texto3: "Reflejar esto en cada elemento del video es lo que al final le brinda contenido de valor y coherencia.",
    procesoSubtitulo2: "2. Producción, acción!",
    procesoSub2Texto1: "Momento de la acción.",
    procesoSub2Texto2: "Todos nuestros talentos están en post de materializar la investigación previa y que el video cobre vida.",
    procesoSub2Texto3: "Cada proyecto es único, puede requerir diseño de sonido, o particular importancia en la música para reforzar el mensaje y el potencial del video.",
    procesoSub2Texto4: "En caso que el proyecto lo requiera, desarrollar un guión y su correspondiente “storyboard.”",
    procesoSubtitulo3: "3. Calidad final del video.",
    procesoSub3Texto1: "Está todo listo y es hora de revisar. De ver mil veces el video final para corregir cualquier error que tienda a ocultarse.",
    procesoSub3Texto2: "En términos de productividad se traduce en eficiencia, porque ahorra tiempo en feedback y afila los detalles que bridan calidad.",
    procesoSub3Texto3: "",
    tituloPortfolio: "Portfolio",
    tituloVideoHor: "Asesores Municipales",
    descVideoHor: "Motion Graphics Descriptivo",
    tituloVideoVer1: "Cara Loren",
    descVideoVer1: "Videos Ads Publicitarios",
    tituloVideoVer2: "Cycle Town",
    descVideoVer2: "Videos Ads Publicitarios",
    tituloVideoCua1: "Evora",
    descVideoCua1: "Videos Ads Publicitarios",
    tituloVideoCua2: "FLY Logística",
    descVideoCua2: "Motion Graphics Descriptivo",
    tituloVideoCua3: "High Fitness",
    descVideoCua3: "Videos Ads Publicitarios",
    tituloContacto: "Contacto",
    inputNombre: "Nombre completo *",
    inputMail: "Mail *",
    inputEmpresa: "Empresa",
    inputMensaje: "Mensaje *",
    botonEnviar: "ENVIAR",
    tituloNosotros: "Nosotros",
    textoNosotros1: "Nuestra satisfacción más grande es trabajar de tal manera que nuestros resultados superen cualquier expectativa.",
    textoNosotros2: "Hemos logrado campañas exitosas mediante nuestros trabajos, en parte porque nos destacamos por la interpretación y buena comunicación con el cliente.",
    textoNosotros3: "Pangea nació con la iniciativa de potenciar emprendimientos amigos, mediante la publicidad audiovisual llegando a impactar positivamente en cada una de sus audiencias.",
    textoNosotros4: "Por eso, actualmente elegimos el mundo de las redes sociales, para impulsar el crecimiento de marcas y empresas, trabajando junto al área de marketing y paid media.",
    textoNosotros5: "",
    botonContactar: "CONTÁCTANOS",
    linkServicios: "Servicios",
    linkPortfolio: "Portfolio",
    linkNosotros: "Nosotros",
    linkContacto: "Contacto",
    linkInicio: "Inicio",
    textoObligatorio: "Este campo es obligatorio."
}

export default es