import { videos } from "./videosEn"

const en = {
    tituloPrincipal: "SERVICES",
    tituloVidSer1: "Creative Design. Testing",
    texto1VidSer1: "Eye-catching visuals, compelling text, and thoughtful editing for a variety of ads: UGC, IGC, testimonials, value props, etc.",
    texto2VidSer1: "This is how we find the optimal message combination.",
    texto3VidSer1: "We continuously test and improve to enhance performance.",
    tituloVidSer2: "Visual Storytelling",
    texto1VidSer2: "Whether in ads or organic content, we leverage the visual nature of Instagram, TikTok, and Facebook to create videos that leave a lasting impression on the relevant audience.",
    tituloVidSer3: "Conversion-Centric",
    texto1VidSer3: "Our content is designed not only to grab attention and maintain retention but also to encourage interaction and drive specific actions.",
    texto1Servicio: "Fluent in the language of design, animation, and video, our uniqueness lies in seamlessly blending these skills with the dynamic realms of marketing and advertising.",
    texto2Servicio: "We meticulously analyze each client's unique needs, crafting solutions that translate into tangible success.",
    textoEmpecemos: "GET STARTED",
    tituloMotion: "A focus on Motion Graphics elevates content success:",
    videosMotion: videos,
    tituloProceso: "Production Process",
    procesoSubtitulo1: "1. First, research",
    procesoSub1Texto1: "It is crucial to dive into the brand's personality, essence, and that of its competitors.",
    procesoSub1Texto2: "In this sea of information, precision paves the way and provides a solid foundation to move forward confidently.",
    procesoSub1Texto3: "",
    procesoSubtitulo2: "2. Production, action!",
    procesoSub2Texto1: "It's time for action.",
    procesoSub2Texto2: "We tailor each project uniquely, whether it's adding bespoke sound design or curating music to amplify the message's impact.",
    procesoSub2Texto3: "For projects demanding it, we script a compelling narrative and bring it to visual life with a meticulously crafted storyboard.",
    procesoSub2Texto4: "",
    procesoSubtitulo3: "3. Final Video Quality",
    procesoSub3Texto1: "With everything in place, it's time for the grand reveal. Watch the final video repeatedly to unveil hidden nuances and correct any subtle errors.",
    procesoSub3Texto2: "This isn't just about productivity; it's about efficiency. It saves time on feedback loops and sharpens the details.",
    procesoSub3Texto3: "Let's create something extraordinary together!",
    tituloPortfolio: "PORTFOLIO",
    tituloVideoHor: "Municipal Advisors",
    descVideoHor: "Descriptive Motion Graphics",
    tituloVideoVer1: "Cara Loren",
    descVideoVer1: "Advertising Video Ads",
    tituloVideoVer2: "Cycle Town",
    descVideoVer2: "Advertising Video Ads",
    tituloVideoCua1: "Evora",
    descVideoCua1: "Advertising Video Ads",
    tituloVideoCua2: "FLY Logística",
    descVideoCua2: "Descriptive Motion Graphics",
    tituloVideoCua3: "High Fitness",
    descVideoCua3: "Advertising Video Ads",
    tituloContacto: "CONTACT",
    inputNombre: "Name *",
    inputMail: "Mail *",
    inputEmpresa: "Company",
    inputMensaje: "Message",
    botonEnviar: "SEND",
    tituloNosotros: "ABOUT US",
    textoNosotros1: "At Pangea, our joy stems from crafting experiences that not only meet but exceed every expectation.",
    textoNosotros2: "Our track record of successful campaigns is a validation of our ability to interpret and communicate effectively with our clients, ensuring their visions come to life.",
    textoNosotros3: "Pangea emerged with a mission - to empower like-minded ventures through the art of audiovisual advertising, leaving a lasting positive impression on diverse audiences.",
    textoNosotros4: "Therefore we've set our sights on social media, leveraging its power to fuel the growth of brands and businesses. Working hand-in-hand with marketing and paid media teams, we're not just storytellers; we're architects of impact, shaping narratives that resonate and drive success.",
    textoNosotros5: "Join us on this journey of creativity and unparalleled results!",
    botonContactar: "CONTACT US",
    linkServicios: "SERVICES",
    linkPortfolio: "PORTFOLIO",
    linkNosotros: "ABOUT US",
    linkContacto: "CONTACT",
    linkInicio: "Home",
    textoObligatorio: "This field is mandatory."
}

export default en