import { videos } from "./videosAnim"

const es = {
    tituloPrincipal: "SERVICIOS",
    tituloVidSer1: "Diseño Creativo. Testeos",
    texto1VidSer1: "Visuales, textos y edición llamativas y pensadas para una gran variedad de anuncios: UGC, IGC, testimoniales, value props, etc.",
    texto2VidSer1: "Así encontramos la combinación óptima del mensaje.",
    texto3VidSer1: "Probamos y mejoramos continuamente para perfeccionar el rendimiento.",
    tituloVidSer2: "Storytelling Visual",
    texto1VidSer2: "Tanto en anuncios, como en orgánico, utilizamos la naturaleza visual de Instagram, TikTok, Facebook, creando videos que provocan una impresión duradera en la audiencia correspondiente.",
    tituloVidSer3: "Centrado en la Conversión",
    texto1VidSer3: "Contenido diseñado no solo para llamar la atención y mantener la retención, sino también para fomentar interacción e impulsar acciones específicas.",
    texto1Servicio: "Hablamos el idioma del diseño, animación y video, pero lo que nos hace únicos es que sabemos conectarlo con el mundo del marketing y la publicidad.",
    texto2Servicio: "Analizamos la necesidad de cada cliente para brindar soluciones reales a objetivos concretos y alcanzar resultados exitosos.",
    textoEmpecemos: "EMPECEMOS",
    tituloMotion: "Un enfoque en Motion Grapchis eleva el éxito del contenido:",
    videosMotion: videos,
    tituloProceso: "Proceso de Producción",
    procesoSubtitulo1: "1. Primero, investigar.",
    procesoSub1Texto1: "Es fundamental investigar la personalidad de la marca, su esencia y la de sus competidores.",
    procesoSub1Texto2: "Permite ser precisos en un mar de información: porque allana el camino y ofrece un terreno sólido sobre el cual avanzar firmemente.",
    procesoSub1Texto3: "Reflejar esto en cada elemento del video es lo que al final le brinda contenido de valor y coherencia.",
    procesoSubtitulo2: "2. Producción, acción!",
    procesoSub2Texto1: "Momento de la acción.",
    procesoSub2Texto2: "Todos nuestros talentos están en post de materializar la investigación previa y que el video cobre vida.",
    procesoSub2Texto3: "Cada proyecto es único, puede requerir diseño de sonido, o particular importancia en la música para reforzar el mensaje y el potencial del video.",
    procesoSub2Texto4: "En caso que el proyecto lo requiera, desarrollar un guión y su correspondiente “storyboard.”",
    procesoSubtitulo3: "3. Calidad final del video.",
    procesoSub3Texto1: "Está todo listo y es hora de revisar. De ver mil veces el video final para corregir cualquier error que tienda a ocultarse.",
    procesoSub3Texto2: "En términos de productividad se traduce en eficiencia, porque ahorra tiempo en feedback y afila los detalles que bridan calidad.",
    procesoSub3Texto3: "",
    tituloPortfolio: "PORTFOLIO",
    tituloVideoHor: "Asesores Municipales",
    descVideoHor: "Motion Graphics Descriptivo",
    tituloVideoVer1: "Cara Loren",
    descVideoVer1: "Videos Ads Publicitarios",
    tituloVideoVer2: "Cycle Town",
    descVideoVer2: "Videos Ads Publicitarios",
    tituloVideoCua1: "Evora",
    descVideoCua1: "Videos Ads Publicitarios",
    tituloVideoCua2: "FLY Logística",
    descVideoCua2: "Motion Graphics Descriptivo",
    tituloVideoCua3: "High Fitness",
    descVideoCua3: "Videos Ads Publicitarios",
    tituloContacto: "CONTACTO",
    inputNombre: "Nombre completo *",
    inputMail: "Mail *",
    inputEmpresa: "Empresa",
    inputMensaje: "Mensaje *",
    botonEnviar: "ENVIAR",
    tituloNosotros: "NOSOTROS",
    textoNosotros1: "Nuestra satisfacción más grande es trabajar de tal manera que nuestros resultados superen cualquier expectativa.",
    textoNosotros2: "Hemos logrado campañas exitosas mediante nuestros trabajos, en parte porque nos destacamos por la interpretación y buena comunicación con el cliente.",
    textoNosotros3: "Pangea nació con la iniciativa de potenciar emprendimientos amigos, mediante la publicidad audiovisual llegando a impactar positivamente en cada una de sus audiencias.",
    textoNosotros4: "Por eso, actualmente elegimos el mundo de las redes sociales, para impulsar el crecimiento de marcas y empresas, trabajando junto al área de marketing y paid media.",
    textoNosotros5: "",
    botonContactar: "CONTÁCTANOS",
    linkServicios: "Servicios",
    linkPortfolio: "Portfolio",
    linkNosotros: "Nosotros",
    linkContacto: "Contacto",
    linkInicio: "Inicio",
    textoObligatorio: "Este campo es obligatorio."
}

export default es